# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python.

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

# Numpy Arrays

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [11]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [12]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [15]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
arr.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [18]:
a = np.array([17, 19, 23, 29, 31, 37, 41, 2, 3, 5, 7, 11, 13])

In [19]:
a.max()

41

In [20]:
a.min()

2

In [21]:
a.argmax()

6

In [22]:
a.argmin()

7

### dtype

In [24]:
j = np.array([1.23, 2.5, 6.9])
j.dtype

dtype('float64')

### Shape

Shape is an attribute that arrays have (not a method):

In [25]:
arr.shape

(4, 3)

## Indexing and Slicing

In [26]:
b = np.array(['abc', 'def', 1, 6.79, 25, 800.0])

In [27]:
b[1]

'def'

In [28]:
b[0:2]

array(['abc', 'def'], dtype='<U5')

## Broadcasting

In [29]:
b[0:2]=10

In [30]:
b

array(['10', '10', '1', '6.79', '25', '800.0'], dtype='<U5')

In [31]:
copy = b.copy()
copy

array(['10', '10', '1', '6.79', '25', '800.0'], dtype='<U5')

In [32]:
copy[1] = 15
copy

array(['10', '15', '1', '6.79', '25', '800.0'], dtype='<U5')

In [33]:
b

array(['10', '10', '1', '6.79', '25', '800.0'], dtype='<U5')

In [34]:
d = b

In [35]:
d[1] = 15
d

array(['10', '15', '1', '6.79', '25', '800.0'], dtype='<U5')

In [36]:
b

array(['10', '15', '1', '6.79', '25', '800.0'], dtype='<U5')

### Indexing a 2D array (matrices)

Format: arr[row][col] or arr[row,col]

In [37]:
arr1 = np.array(([1,2,3],[4,5,6],[7,8,9]))

arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
#Indexing row
arr1[:][1]

array([4, 5, 6])

In [42]:
# Accessing element
arr1[2][2]

9

In [43]:
arr1[:2,1:]

array([[2, 3],
       [5, 6]])

## Arithmetic

In [44]:
arr = np.arange(0,10)

In [45]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [47]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
arr/arr

/home/sujay/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [50]:
1/arr

/home/sujay/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

## Array Methods

In [51]:
# Square roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [52]:
# Exponential values
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [53]:
# Max value
np.max(arr) 

9

In [54]:
# Sine values
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [55]:
# Log values
np.log(arr)

/home/sujay/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])